version: 2.1

references:
  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}-{{ checksum  "core/build.gradle.kts" }}-{{ checksum  "data/build.gradle.kts" }}

jobs:
  build_and_test:
    docker:
      - image: circleci/android:api-30
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3200m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
      - run:
          name: Export google-services.json
          command: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json
      - run:
          name: Assemble
          command: ./gradlew assemble
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
        name: Save test results
        command: |
          mkdir -p ~/test-results/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
        when: always
          - store_test_results:
              path: ~/test-results
          - store_artifacts:
              path: ~/test-results/junit

workflows:
  build_and_test:
    jobs:
      - build_and_test